services:
  - type: web
    name: jtdevtracker
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: node server/index.js
    envVars:
      - key: DB_HOST
        value: 127.0.0.1
      - key: DB_PORT
        value: "3306"
      - key: DB_USER
        value: root
      - key: DB_PASSWORD
        value: Blusmak1
      - key: DB_NAME
        value: jtdevtracker
      - key: DB_TABLE
        value: jtdevtracker1
    autoDeploy: true