CREATE DATABASE IF NOT EXISTS jtdevtracker
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE jtdevtracker;

CREATE TABLE IF NOT EXISTS jtdevtracker1 (
  id TINYINT UNSIGNED NOT NULL PRIMARY KEY,
  updated_at BIGINT NOT NULL,
  projects_json JSON NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  modified_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

INSERT INTO jtdevtracker1 (id, updated_at, projects_json)
VALUES (1, UNIX_TIMESTAMP() * 1000, JSON_ARRAY())
ON DUPLICATE KEY UPDATE id = id;
